title: JB Manager Dokumentation
description: Eine Dokumentation für die Anwendung JB Manager
theme: just-the-docs

url: https://jannes115.github.io/jb

aux_links:
  Template Repository: https://github.com/jannes115/jb
